# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c47d709f860f50011014c9600cf4fb3fd4aaf860382b291cd0c6248874c2aaf96b4e690d995c637e849d229b3fe1fdd93a7d6efa309d8bc3bb871df4da28009

test:
  secret_key_base: e7b5611ab98cdc3a0608db29ff023618b3008af372bb1535efc9b366189a8e495f7d4ed40724880195be9380fc9caf61447a28fb3454560fc14b8f8702313eb6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
